name: test

on:
  pull_request:

  push:
    branches:
      - main

  workflow_call:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-cuda:
    name: CUDA ${{ matrix.cuda }}
    runs-on: ubuntu-24.04
    container:
      image: nvidia/cuda:${{ matrix.cuda }}-devel-ubuntu24.04
    strategy:
      fail-fast: false
      matrix:
        cuda: ["12.8.1"]
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get install --yes cmake
      - uses: actions/checkout@v6
      - name: Build and install
        uses: ./.github/actions/build-install
        with:
          platform: "nvidia"

  build-hip:
    name: ROCm ${{ matrix.rocm }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rocm: ["7.2"]
    steps:
      - name: Find ROCm repository
        id: set-rocm-repo
        run: |
          rocmdeb=$(grep "^${{ matrix.rocm }} " radeon-repo.txt | awk '{print $2}')
          if [[ -n $rocmdeb ]]; then
            echo "rocmdeb=$rocmdeb" >> $GITHUB_OUTPUT
          else
            echo "Unknown ROCm version" && exit 1
          fi
      - name: Install ROCm
        run: |

          wget ${{ steps.set-rocm-repo.outputs.rocmdeb }} -O amdgpu-install.deb
          sudo apt-get install --yes ./amdgpu-install.deb
          sudo apt-get update
          sudo apt-get install --yes rocm-hip-sdk

          sudo tee --append /etc/ld.so.conf.d/rocm.conf <<EOF
          /opt/rocm/lib
          /opt/rocm/lib64
          EOF
          sudo ldconfig
      - name: Install build dependencies
        run: |
          sudo apt-get install --yes cmake
      - uses: actions/checkout@v6
      - name: Build and install
        uses: ./.github/actions/build-install
        with:
          platform: "amd"
