name: test

on:
    pull_request:

    push:
        branches:
            - main

    workflow_call:

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    build-cuda:
        name: build [CUDA ${{ matrix.cuda }}]
        runs-on: ubuntu-24.04
        container:
            image: nvidia/cuda:${{ matrix.cuda }}-devel-ubuntu24.04
        strategy:
            fail-fast: false
            matrix:
                cuda: ["12.8.1", "13.1.1"]
        steps:
            - name: Setup environment
              run: |
                  apt-get update
                  apt-get install --yes cmake
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Configure
              run: |
                  cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
            - name: Build
              run: |
                  cmake --build build
            - name: Install
              run: |
                  cmake --install build
